# Stubs for django.contrib.gis.gdal (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.gdal.envelope import Envelope as Envelope
from django.contrib.gis.gdal.error import GDALException as GDALException, OGRException as OGRException, OGRIndexError as OGRIndexError, SRSException as SRSException, check_err as check_err
from django.contrib.gis.gdal.geomtype import OGRGeomType as OGRGeomType

HAS_GDAL = ...  # type: bool
